name: install bazelisk

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  instal-bazelisk:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Bazelisk action
        uses: actions/checkout@v2
        with:
          repository: promiseofcake/bazelisk-action
          path: ./.github/actions/bazelisk-action
          ref: 'ljk/improve-inputs'
      - name: Setup Bazelisk
        uses: ./.github/actions/bazelisk-action
        with:
          os: ${{ runner.os }}
      - name: Bazel info
        run: bazel info
