name: expressions workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  helloWorld:
    runs-on: ubuntu-latest
    env:
      FOO: foo
      BAR: bar
      BAZ: baz
    steps:
    - run: |
        echo '{"build_workflow": "${{ env.FOO }}"}'
